### ISSUE TITLE
This docker-compose uses mod_php

### ISSUE THREAD

**Issue by qmaxquique** [dpfaffenbauer/pimcore-docker-compose#8]
**First and foremost, thanks for maintaining this repo!**

I've noticed that the readme says that you're using Apache and php-fpm but your docker-compose file uses the image with mod-php (and mpm prefork) Do you think you can build a compose file to use apache with mpm event and php-fpm?

Thank you!

**Comment by dpfaffenbauer** [comment]
Well, there are following configurations available:

 - PHP 7.1 FPM + Apache + Maria
 - PHP 7.1 Apache + Maria
 - PHP 7.2 FPM + Apache + Maria
 - PHP 7.2 Apache + Maria

I guess you are talking about the first and third one right?

You can use this configuration then:

```yml
version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: pimcore-redis

  mariadb:
    image: mariadb:10.1
    container_name: pimcore-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - .:/var/www/html:cached
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  webserver:
    image: httpd
    container_name: pimcore-webserver
    working_dir: /application
    volumes:
        - .:/var/www/html:cached
        - ./.docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./.docker/apache/pimcore.conf:/usr/local/apache2/conf/sites-enabled/100-pimcore.conf
    ports:
     - "2000:80"
    links:
      - php-fpm:php-fpm

  php-fpm:
    build: dpfaffenbauer/pimcore-docker-php-fpm:PHP7.1
    container_name: pimcore-php-fpm
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
    links:
     - mariadb:mariadb
     - redis:redis

volumes:
  pimcore-database:
```
**BUT:** This is not tested, So I am not sure if its 100% right.

The reason I switched from FPM to mod-php is permission issues inside the containers.
